### ISSUE TITLE
ShopwarePayone error for credit card payment in protected function validateRequest in MoptPaymentPayone/Components/Payone/TransactionStatus/Service/HandleRequest.php

### ISSUE THREAD

**Issue by irwinbraganza** [PAYONE-GmbH/shopware-5#238]
I am facing this issue in shopware version 5.5.1 and paypone plugin version: 3.11.0:
`18 Oct 2018 12:12:26.414<14>1 2018-10-18T06:42:26.379941Z 141.0.20.206 ShopwarePayone - - - [2018-10-18 08:42:26] moptPayone.ERROR: error processing request ["#0 /var/www/html/production/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Components/Payone/TransactionStatus/Service/HandleRequest.php(118): Payone_TransactionStatus_Validator_Ip->validateRequest(Object(Payone_TransactionStatus_Request))\n#1 /var/www/html/production/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Components/Payone/TransactionStatus/Service/HandleRequest.php(95): Payone_TransactionStatus_Service_HandleRequest->validateRequest(Object(Payone_TransactionStatus_Request))\n#2 /var/www/html/production/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Components/Payone/TransactionStatus/Service/HandleRequest.php(83): Payone_TransactionStatus_Service_HandleRequest->handle(Object(Payone_TransactionStatus_Request))\n#3 /var/www/html/production/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Controllers/Frontend/MoptShopNotification.php(101): Payone_TransactionStatus_Service_HandleRequest->handleByPost()\n#4 /var/www/html/production/engine/Library/Enlight/Controller/Action.php(193): Shopware_Controllers_Frontend_MoptShopNotification->indexAction()\n#5 /var/www/html/production/engine/Library/Enlight/Controller/Dispatcher/Default.php(549): Enlight_Controller_Action->dispatch('indexAction')\n#6 /var/www/html/production/engine/Library/Enlight/Controller/Front.php(222): Enlight_Controller_Dispatcher_Default->dispatch(Object(Enlight_Controller_Request_RequestHttp), Object(Enlight_Controller_Response_ResponseHttp))\n#7 /var/www/html/production/engine/Shopware/Kernel.php(202): Enlight_Controller_Front->dispatch()\n#8 /var/www/html/production/vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(102): Shopware\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#9 /var/www/html/production/vendor/symfony/http-kernel/HttpCache/HttpCache.php(448): Symfony\\Component\\HttpKernel\\HttpCache\\SubRequestHandler::handle(Object(Shopware\\Kernel), Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#10 /var/www/html/production/engine/Shopware/Components/HttpCache/AppCache.php(268): Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache->forward(Object(Symfony\\Component\\HttpFoundation\\Request), true, NULL)\n#11 /var/www/html/production/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Shopware\\Components\\HttpCache\\AppCache->forward(Object(Symfony\\Component\\HttpFoundation\\Request), true)\n#12 /var/www/html/production/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache->pass(Object(Symfony\\Component\\HttpFoundation\\Request), true)\n#13 /var/www/html/production/engine/Shopware/Components/HttpCache/AppCache.php(143): Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache->invalidate(Object(Symfony\\Component\\HttpFoundation\\Request), true)\n#14 /var/www/html/production/vendor/symfony/http-kernel/HttpCache/HttpCache.php(181): Shopware\\Components\\HttpCache\\AppCache->invalidate(Object(Symfony\\Component\\HttpFoundation\\Request), true)\n#15 /var/www/html/production/engine/Shopware/Components/HttpCache/AppCache.php(116): Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#16 /var/www/html/production/shopware.php(122): Shopware\\Components\\HttpCache\\AppCache->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#17 {main}"] []`

**Comment by irwinbraganza** [comment]
can anyone here please help?

**Comment by irwinbraganza** [comment]
Thank you @hreinberger, After talking to tech support team it seemed to be the issue with request been manupulated by your proxy/load balancer/caching system ( in our case cloud flare) we faced. fixed it by disabling it :) Closing this issue.
