### ISSUE TITLE
Broken Orders with Paypal

### ISSUE THREAD

**Issue by KevinHansen23** [PAYONE-GmbH/shopware-5#499]
Hi,

in some rare cases when a customers pays with Paypal the following Error occurs:

```
[14-Jul-2023 07:55:49 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function setMoptPayoneShipCaptured() on null in /.../shopware/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Components/Classes/PayonePaymentHelper.php:1679
Stack trace:
#0 /.../shopware/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Controllers/Frontend/MoptPaymentPayone.php(1050): Mopt_PayonePaymentHelper->markOrderDetailsAsFullyCaptured(Object(Shopware\Models\Order\Order))
#1 /.../shopware/engine/Library/Enlight/Controller/Action.php(192): Shopware_Controllers_Frontend_MoptPaymentPayone->finishOrderAction()
#2 /.../shopware/engine/Library/Enlight/Controller/Dispatcher/Default.php(478): Enlight_Controller_Action->dispatch('finishOrderActi...')
#3 /.../shopware/engine/Library/Enlight/Controller/Front.php(228): Enlight_Controller_Dispatcher_Default->dispatch(Object(Enlight_Controller_Request_RequestHttp), Object(Enlight_Controller_Response_ResponseHtt in /.../shopware/engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Components/Classes/PayonePaymentHelper.php on line 1679
```

Everytime this Error occurs the payment has been processed but there are two broken orders in the Shopware Database. To this point it always has been Paypal as payment method.

Plugin Version: 4.11.0
Shop Version: 5.6.9

**Comment by dmetoglou** [comment]
Since payment related data is involved, kindly forward your issue to PAYONE tech Support to investigate further.

**Comment by KevinHansen23** [comment]
I can do that, but there is no error on Payones side. In the Merchant Center everything looks fine.
